### ISSUE TITLE
Broken authentification

### ISSUE THREAD

**Issue by likeitneverwentaway** [YunoHost-Apps/radicale_ynh#5]
L'authentication par mot de passe sur Infcloud (LDAP ?) ne marche pas, on peut se connecter à un user avec n'importe quel pass... Peut être une dupplicate de #2  ?

Merci pour ce package en tout cas! :+1:

**Comment by maniackcrudelis** [comment]
Effectivement...!
C'est pourtant quelque chose que j'avais vérifié, il y a de la régression quelque part...

Je m'occupe de ça en priorité

**Comment by maniackcrudelis** [comment]
Après analyse de la situation, il semblerais que cet accès avec n'importe quel mot de passe soit lié à la configuration de radicale.

Mais, en réalité, ce n'est que l'accès lecture seule qui est autorisé, pas l'accès en écriture.
D'après mes essais, seul l'user authentifié sur le SSO et ayant donné le bon mot de passe sur infcloud peut écrire sur les calendriers.

J'imagine que c'est lié à la première règle du fichier right.
https://github.com/YunoHost-Apps/radicale_ynh/blob/master/conf/rights#L11-L15
Celle-ci autorise la lecture de l'ensemble de la collection à tout utilisateur authentifié. Or celui-ci l'est via le SSO.

Toutefois, cette règle est nécessaire pour qu'un user soit capable de voir le dossier de ses calendriers. Et ensuite obtenir un droit d'écriture sur son dossier.

Les règles d'accès de radicale sont assez complexe à gérer...

Je veux bien que tu fasses un essai en écriture pour t'assurer que seul l'user propriétaire des calendriers a le droit d'écriture.

PS: Je dois bien avouer que pour le moment, je n'ai pas réussi à autoriser la découverte du dossier user sans cette règle qui est très large. Et ce fichier manque cruellement de documentation...

**Comment by likeitneverwentaway** [comment]
> J'imagine que c'est lié à la première règle du fichier right.

Oui c'est ce que je pensais aussi. Du coup le problème est résolu si on saute le login via le SSO: si c'est pas le bon mdp on a le droit à un popup d'identification (c'est le http basic login non ?), donc on peut pas acceder aux calendrier vu que ca ne marche pas. Si on rentre le bon mdp dans infcloud alors c'est ok.

Par contre si je suis authentifié via le SSO j'ai quand même le droit d'écriture avec le mauvais mdp, et je n'ai aucune règle qui permettent l'écriture dans le rights...

La solution est donc de sauter le sauter le SSO pour l'app, mais pourtant même après avoir fait `sudo yunohost app setting radicale unprotected_uris -v "/"`, `sudo yunohost app ssowatconf` et restart nginx je suis toujours redirigé vers le portail... Une idée ?

**Comment by maniackcrudelis** [comment]
> Par contre si je suis authentifié via le SSO j'ai quand même le droit d'écriture avec le mauvais mdp, et je n'ai aucune règle qui permettent l'écriture dans le rights...

Tu devrais avoir un droit d'écriture uniquement sur tes propres calendriers.
Mais tu as un droit de lecture sur les calendriers de tout user.

En somme, l'identification ne sert à rien derrière le SSO. Et l'idéal serait vraiment de réussir à configurer le module HTTP AUTH. Ça éviterais d'obtenir un droit de lecture sur les autres calendriers aussi facilement...

> Edit: ca y est j'ai trouvé, yunohost app setting -d radicale protected_uris . Du coup je sais pas si cette ligne est pas en trop...

Non, `protected_uris -v "/"` protège l'accès à infcloud, tandis que `unprotected_regex -v "$domain_regex$path"` rend public l'accès à radicale.

Donc si tu supprimes protected_uris, effectivement tu ne protèges plus infcloud. On est effectivement sur une authentification en http basic, qui est fournie par radicale.
Du moins en principe, en ce qui me concerne, je tombe toujours sur la même page de login de infcloud.

**Comment by likeitneverwentaway** [comment]
> Donc si tu supprimes protected_uris, effectivement tu ne protèges plus infcloud. On est effectivement sur une authentification en http basic, qui est fournie par radicale.

En tout cas sans authentification SSO et juste sur infcloud, les logs disent que c'est une authentification avec les données LDAP. Après c'est peut-être ce que tu voulais dire je connais pas trop la méthode http basic. ;) Mais oui ce serait l'idéal, dans mon cas j'ai link tout les calendriers d'un user et supprimer la toute première règle pour empécher d'avoir un droit en écriture... C'est la galère.

**Comment by maniackcrudelis** [comment]
Oui c'est une authentification ldap via radicale, infcloud n'est pas connecté à ldap.
Mais c'est du http basic, c'est pas chiffré. C'est le certificat SSL qui sécurise la communication par dessus.

Si tu supprimes la première règle, tu risques de pas avoir accès aux ressources, car il ne trouvera pas les dossiers contenant les calendriers.

Si tu veux regarder, il y a une "explication" [ici](https://www.inf-it.com/infcloud/readme.txt), à la section 6.
Ça concerne le fichier `/var/www/radicale/infcloud/auth/config.inc` avant tout
