### ISSUE TITLE
automatic login

### ISSUE THREAD

**Issue by dune11** [YunoHost-Apps/radicale_ynh#8]
Hello.
I use infcloud as a single user. Is it possible after autostart infcloud to Login automatically?

dune11

**Comment by maniackcrudelis** [comment]
[Infcloud](https://www.inf-it.com/open-source/clients/infcloud/) is supposed to be able to handle HTTP authentification.
But I haven't found the way to do it so far.

**Comment by alexAubin** [comment]
Closing as duplicated
